# Generated by Django 4.0.3 on 2022-03-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('parent_phone', models.CharField(max_length=122)),
                ('parent_email', models.EmailField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=255)),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('is_approved', models.BooleanField()),
                ('approved_by', models.CharField(max_length=122)),
                ('food_group', models.CharField(max_length=122)),
                ('kid_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myfoodapp.kid')),
            ],
        ),
    ]
