# Generated by Django 4.0.3 on 2022-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0002_image_img_alter_image_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default='DEFAULT', upload_to=''),
        ),
    ]
