# Generated by Django 4.0.3 on 2022-03-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0006_remove_image_img_alter_image_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='updated_on',
        ),
    ]
