# Generated by Django 4.0.3 on 2022-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0007_remove_image_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='food_group',
            field=models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAIN', 'Grain'), ('PROTEIN', 'Protein'), ('DAIRY', 'Dairy'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
