# Generated by Django 4.0.3 on 2022-03-20 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0008_alter_image_food_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
