# Generated by Django 4.0.3 on 2022-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfoodapp', '0009_image_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
